/**
 * v1 videos + photos module for mp/media.html — renderVideos, lightbox, tabs, inline/modal playback (EN, static JSON).
 * Data: /v1-assets/data/media-data.json — generated by scripts/build-media.js from admin export
 * rg_vid, rg_photos, rg_photo_captions, optional rg_ui_en (EN chrome); defaults in v1-assets/build/media-defaults.json.
 * After loading that file, videos merge from Firestore rg / rg_vid (canonical), with fallback to rg / rg_vid_en when rg_vid
 * has no videos (same merge rule as admin-v2). Photos + captions merge from rg_photos and rg_photo_captions when readable
 * (same REST pattern as mp-hero.js), so admin-v2 saves show on the public Media page without re-running build:media.
 */
(function () {
  'use strict';

  var MP_MEDIA = null;
  var currentLang = 'en';
  var FIRESTORE_PROJECT_ID = 'rolandoguy-57d63';

  function mpPick(lang, key, fb) {
    var p = window.pickMpLocaleString;
    if (p) {
      var v = p(lang, key);
      if (v != null && String(v).trim() !== '') return v;
    }
    return fb;
  }

  function mpUiTable(lang, defaults) {
    var t = {};
    for (var k in defaults) {
      if (Object.prototype.hasOwnProperty.call(defaults, k)) t[k] = mpPick(lang, k, defaults[k]);
    }
    return t;
  }

  var MP_MEDIA_UI_EN = {
    'vid.brand': 'Rolando Guy · Lyric Tenor',
    'vid.cat.opera_lied': 'Opera & Art Song',
    'vid.cat.gala_crossover': 'Gala & Crossover',
    'vid.repCat.opera': 'Opera',
    'vid.repCat.lied': 'Lied & art song',
    'vid.repCat.concert_sacred': 'Concert & sacred',
    'vid.repCat.tango': 'Tango',
    'vid.repCat.crossover': 'Crossover',
    'vid.showMore': '+ Show More Videos',
    'vid.showLess': '\u2212 Show Less',
    'vid.embedUnavailable': 'Video player unavailable',
    'vid.openYoutube': 'Open on YouTube',
    'ui.close': 'Close \u2715',
    'ui.closeEmbed': '\u00d7 Close',
    'ui.closeVideoAria': 'Close video'
  };

  function uiTable(lang) {
    var L = lang || currentLang || 'en';
    return mpUiTable(L, MP_MEDIA_UI_EN);
  }

  function effectiveUiText(lang, key) {
    var L = lang || currentLang || 'en';
    return mpPick(L, key, MP_MEDIA_UI_EN[key]);
  }

  function formatSectionTitleIfAmpersand(html, i18nKey) {
    var s = String(html || '');
    if (i18nKey === 'programs.sectionTag') return s;
    if (!s || /class=["']title-amp-stack["']/.test(s)) return s;
    var splitIdx = s.indexOf('&amp;');
    var ampLen = 5;
    if (splitIdx === -1) {
      var m = s.match(/&(?!amp;|#?[0-9a-z]+;)/i);
      if (!m || m.index == null) return s;
      splitIdx = m.index;
      ampLen = 1;
    }
    var left = s.slice(0, splitIdx);
    var right = s.slice(splitIdx + ampLen);
    left = left.replace(/<br\s*\/?>(\s*)/gi, ' ').replace(/&nbsp;/gi, ' ').trim();
    right = right.replace(/^(\s|<br\s*\/?>|&nbsp;)+/i, '').trim();
    var leftText = left.replace(/<[^>]+>/g, '').replace(/\s+/g, ' ').trim();
    var esc = function (t) {
      return String(t)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
    };
    return (
      '<span class="title-amp-stack"><span class="title-line1">' +
      esc(leftText) +
      '</span><span class="title-line2"><span class="title-amp">&amp;</span> ' +
      right +
      '</span></span>'
    );
  }

  function withTitleEmphasisVid(vidH2) {
    var raw = String(vidH2 || '').trim();
    return formatSectionTitleIfAmpersand(raw);
  }

  function getVid() {
    return MP_MEDIA && MP_MEDIA.vid && typeof MP_MEDIA.vid === 'object'
      ? MP_MEDIA.vid
      : { h2: '', videos: [] };
  }

  function resolvePhotoSrc(x) {
    if (x == null) return '';
    if (typeof x === 'string') return x;
    if (typeof x === 'object' && x.url != null) return String(x.url);
    return '';
  }

  function getPhotoPaths() {
    if (!MP_MEDIA || !MP_MEDIA.photos) return { s: [], t: [], b: [] };
    var p = MP_MEDIA.photos;
    function list(arr) {
      return (Array.isArray(arr) ? arr : []).map(resolvePhotoSrc);
    }
    return { s: list(p.s), t: list(p.t), b: list(p.b) };
  }

  function fetchFirestoreRgDoc(key) {
    var url =
      'https://firestore.googleapis.com/v1/projects/' +
      FIRESTORE_PROJECT_ID +
      '/databases/(default)/documents/rg/' +
      encodeURIComponent(key);
    return fetch(url, { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) return null;
        return r.json();
      })
      .then(function (doc) {
        var v = doc && doc.fields && doc.fields.value && doc.fields.value.stringValue;
        if (!v || typeof v !== 'string') return null;
        try {
          return JSON.parse(v);
        } catch (e) {
          return null;
        }
      })
      .catch(function () {
        return null;
      });
  }

  function normalizeLivePhotosBlock(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
    var s = Array.isArray(raw.s) ? raw.s.map(resolvePhotoSrc) : [];
    var t = Array.isArray(raw.t) ? raw.t.map(resolvePhotoSrc) : [];
    var b = Array.isArray(raw.b) ? raw.b.map(resolvePhotoSrc) : [];
    if (!s.length && !t.length && !b.length) return null;
    return { s: s, t: t, b: b };
  }

  function normalizeLiveCaptions(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
    var out = {};
    for (var k in raw) {
      if (!Object.prototype.hasOwnProperty.call(raw, k)) continue;
      var v = raw[k];
      if (typeof v === 'string') {
        out[k] = { caption: v, alt: '', photographer: '' };
        continue;
      }
      if (v && typeof v === 'object') {
        out[k] = {
          caption: String(v.caption != null ? v.caption : ''),
          alt: String(v.alt != null ? v.alt : ''),
          photographer: String(v.photographer != null ? v.photographer : '')
        };
      }
    }
    return Object.keys(out).length ? out : null;
  }

  /** Same field shape as admin-v2 safeMediaVideos; returns null if no usable videos (keeps static JSON). */
  function normalizeLiveVidBlock(raw) {
    if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return null;
    var h2 = String(raw.h2 != null ? raw.h2 : '').trim();
    var arr = Array.isArray(raw.videos) ? raw.videos : [];
    var videos = arr
      .filter(function (v) {
        return v && typeof v === 'object' && !Array.isArray(v);
      })
      .map(function (v) {
        var group = String(v.group != null ? v.group : '').trim();
        return {
          id: String(v.id != null ? v.id : '').trim(),
          tag: String(v.tag != null ? v.tag : '').trim(),
          title: String(v.title != null ? v.title : '').trim(),
          sub: String(v.sub != null ? v.sub : '').trim(),
          composer: String(v.composer != null ? v.composer : '').trim(),
          repertoireCat: String(v.repertoireCat != null ? v.repertoireCat : '').trim(),
          hidden: !!v.hidden,
          group: group || 'opera_lied',
          featured: !!v.featured,
          customThumb: String(v.customThumb != null ? v.customThumb : '').trim(),
          editorialStatus: String(
            v.editorialStatus != null ? v.editorialStatus : v.hidden ? 'hidden' : 'draft'
          )
        };
      });
    if (!videos.length) return null;
    return { h2: h2, videos: videos };
  }

  /** Canonical rg_vid; if empty, legacy rg_vid_en (matches admin-v2 mergeRgVidRead). */
  function mergeLiveVidFromFirestore(primaryRaw, legacyEnRaw) {
    var primary = normalizeLiveVidBlock(primaryRaw);
    if (primary) return primary;
    return normalizeLiveVidBlock(legacyEnRaw);
  }

  function applyLiveMediaOverridesFromFirestore() {
    return Promise.all([
      fetchFirestoreRgDoc('rg_photos'),
      fetchFirestoreRgDoc('rg_photo_captions'),
      fetchFirestoreRgDoc('rg_vid'),
      fetchFirestoreRgDoc('rg_vid_en')
    ]).then(function (quads) {
      if (!MP_MEDIA) return;
      var livePhotos = normalizeLivePhotosBlock(quads[0]);
      var liveCaps = normalizeLiveCaptions(quads[1]);
      var liveVid = mergeLiveVidFromFirestore(quads[2], quads[3]);
      if (liveVid) {
        if (!MP_MEDIA.vid) MP_MEDIA.vid = { h2: '', videos: [] };
        var jsonH2 =
          MP_MEDIA.vid && typeof MP_MEDIA.vid.h2 === 'string' ? String(MP_MEDIA.vid.h2).trim() : '';
        MP_MEDIA.vid.h2 = liveVid.h2 || jsonH2;
        MP_MEDIA.vid.videos = liveVid.videos;
      }
      if (!livePhotos && !liveCaps) return;
      if (!MP_MEDIA.photos) MP_MEDIA.photos = {};
      if (livePhotos) {
        MP_MEDIA.photos.s = livePhotos.s;
        MP_MEDIA.photos.t = livePhotos.t;
        MP_MEDIA.photos.b = livePhotos.b;
      }
      if (liveCaps) {
        MP_MEDIA.photos.captions = Object.assign({}, MP_MEDIA.photos.captions || {}, liveCaps);
      }
    });
  }

  function getCaptions() {
    return (MP_MEDIA && MP_MEDIA.photos && MP_MEDIA.photos.captions) || {};
  }

  function getCaption(type, idx) {
    var caps = getCaptions();
    var raw = caps[type + '_' + idx];
    if (typeof raw === 'string') return { caption: raw, alt: '', photographer: '' };
    if (!raw || typeof raw !== 'object') return { caption: '', alt: '', photographer: '' };
    return {
      caption: String(raw.caption || ''),
      alt: String(raw.alt || ''),
      photographer: String(raw.photographer || '')
    };
  }

  var VIDEO_REP_CATS = ['opera', 'lied', 'concert_sacred', 'tango', 'crossover'];
  function videoBlobLower(v) {
    return [v.tag, v.title, v.sub]
      .map(function (x) {
        return String(x || '');
      })
      .join(' ')
      .toLowerCase();
  }
  function inferTangoFromBlob(blob) {
    return /\btango\b|milonga|bandoneon|bandoneón|tango argentin|tango argentino|tangos\b|tango-loft|tango loft/.test(
      blob
    );
  }
  function resolveVideoRepertoireCat(v) {
    var raw = String(v.repertoireCat || '').trim();
    if (raw === 'tango_crossover') {
      var bb = videoBlobLower(v);
      raw = inferTangoFromBlob(bb) ? 'tango' : 'crossover';
    }
    if (VIDEO_REP_CATS.indexOf(raw) !== -1) return raw;
    var blob = videoBlobLower(v);
    if (v.group === 'gala_crossover') return inferTangoFromBlob(blob) ? 'tango' : 'crossover';
    if (
      /\blied\b|kunstlied|art song|lorelei|schubert|schumann|wolf|liederabend|mélodie|melodie|canción de arte|kunstlie/.test(
        blob
      )
    )
      return 'lied';
    if (
      /sacred|oratorio|requiem|\bmass\b|bach|motet|passion|stabat|kirche|kirch|church|cathedral|\bmesse\b|geistlich|sacro|sacrée|sacra/.test(
        blob
      )
    )
      return 'concert_sacred';
    return 'opera';
  }

  function escVideoHtml(s) {
    return String(s == null ? '' : s)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');
  }
  function escVideoAttr(s) {
    return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
  }

  function renderVideos() {
    var d = getVid();
    var t = uiTable(currentLang);
    var locH2 = mpPick(currentLang, 'mp.videos.h2', '');
    var vidH2 =
      locH2 && String(locH2).trim()
        ? locH2
        : d && typeof d.h2 === 'string' && d.h2.trim()
          ? d.h2
          : '';
    var vidH2el = document.getElementById('vidH2');
    if (vidH2el) vidH2el.innerHTML = withTitleEmphasisVid(vidH2);
    var vids = Array.isArray(d.videos) ? d.videos.slice() : [];
    var grid = document.getElementById('videoGrid');
    var more = document.getElementById('videoMore');
    if (!grid || !more) return;

    function mkCard(v, i, hidden) {
      var baseCls = 'video-card reveal' + (i > 0 ? ' rd' + i : '');
      var cls = v.featured ? baseCls + ' video-card-featured' : baseCls;
      var st = hidden ? ' style="display:none;max-width:500px;margin:4px auto 0"' : '';
      var brandRaw = t['vid.brand'] || 'Rolando Guy · Lyric Tenor';
      var brand = escVideoHtml(brandRaw);
      var repCat = resolveVideoRepertoireCat(v);
      var catKey = 'vid.repCat.' + repCat;
      var catLabel = escVideoHtml(t[catKey] || repCat.replace(/_/g, ' '));
      var vidId = String(v.id || '').trim();
      var custom = v.customThumb && String(v.customThumb).trim() ? String(v.customThumb).trim() : '';
      var thumbSrc = custom || (vidId ? 'https://i.ytimg.com/vi/' + vidId + '/maxresdefault.jpg' : '');
      var hqFallback = vidId ? 'https://i.ytimg.com/vi/' + vidId + '/hqdefault.jpg' : '';
      var imgHtml = thumbSrc
        ? '<img class="video-thumb-media" src="' +
          escVideoAttr(thumbSrc) +
          '" alt="" loading="lazy" decoding="async"' +
          (hqFallback
            ? ' onerror="if(this.dataset._vfb!==\'1\'){this.dataset._vfb=\'1\';this.src=\'' +
              escVideoAttr(hqFallback) +
              '\';}else{this.style.visibility=\'hidden\';}"'
            : '') +
          '>'
        : '';
      var hasCustom = !!custom;
      var title = escVideoHtml(v.title);
      var composer = v.composer && String(v.composer).trim() ? escVideoHtml(String(v.composer).trim()) : '';
      var sub = v.sub && String(v.sub).trim() ? escVideoHtml(String(v.sub).trim()) : '';
      var wrapCls = 'video-thumb-wrap video-cat-' + repCat + (hasCustom ? ' video-has-custom' : '');
      return (
        '<div class="' +
        cls +
        '" ' +
        st +
        '>' +
        '<div class="' +
        wrapCls +
        '" id="vwrap-' +
        escVideoAttr(vidId) +
        '">' +
        imgHtml +
        '<div class="video-thumb-scrim" aria-hidden="true"></div>' +
        '<span class="video-cat-pill">' +
        catLabel +
        '</span>' +
        '<div class="video-thumb-overlay">' +
        '<div class="video-brand">' +
        brand +
        '</div>' +
        '<div class="video-meta-title">' +
        title +
        '</div>' +
        (composer ? '<div class="video-meta-composer">' + composer + '</div>' : '') +
        (sub ? '<div class="video-meta-sub">' + sub + '</div>' : '') +
        '</div>' +
        '<div class="video-play-btn" onclick="playVideo(\'' +
        escVideoAttr(vidId) +
        '\', event)" style="cursor:pointer;position:absolute;inset:0;display:flex;align-items:center;justify-content:center">' +
        '<div class="play-circle">' +
        '<svg width="14" height="16" viewBox="0 0 16 18"><path d="M0 0L16 9L0 18V0Z" fill="currentColor"/></svg>' +
        '</div></div></div>' +
        '<div class="video-info-bar">' +
        '<div class="video-tag">' +
        escVideoHtml(v.tag) +
        '</div>' +
        '<div class="video-title">' +
        title +
        '</div>' +
        '<div class="video-sub">' +
        sub +
        '</div>' +
        '</div></div>'
      );
    }

    var normalised = vids.map(function (v) {
      var group = v.group || '';
      if (!group) {
        var title = String(v.title || '');
        if (/libiamo/i.test(title)) group = 'gala_crossover';
        else group = 'opera_lied';
      }
      var o = {};
      for (var k in v) {
        if (Object.prototype.hasOwnProperty.call(v, k)) o[k] = v[k];
      }
      o.group = group;
      return o;
    });

    var groups = [
      { key: 'opera_lied', label: t['vid.cat.opera_lied'] || 'Opera & Art Song' },
      { key: 'gala_crossover', label: t['vid.cat.gala_crossover'] || 'Gala & Crossover' }
    ];

    var htmlVisible = '';
    var htmlHidden = '';

    function orderVideoGroupEntries(entries) {
      return entries.slice().sort(function (a, b) {
        var fa = a.v.featured ? 0 : 1;
        var fb = b.v.featured ? 0 : 1;
        if (fa !== fb) return fa - fb;
        return a.idx - b.idx;
      });
    }

    groups.forEach(function (gconf) {
      var entries = normalised
        .map(function (v, idx) {
          return { v: v, idx: idx };
        })
        .filter(function (e) {
          return (e.v.group || 'opera_lied') === gconf.key;
        });
      if (!entries.length) return;

      var ordered = orderVideoGroupEntries(entries).map(function (e) {
        return e.v;
      });
      var vis = ordered.filter(function (v) {
        return !v.hidden;
      });
      var hid = ordered.filter(function (v) {
        return v.hidden;
      });

      var secTitle = String(gconf.label || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
      if (vis.length) {
        htmlVisible +=
          '<div class="video-category">' +
          '<h3 class="video-category-title">' +
          secTitle +
          '</h3>' +
          vis
            .map(function (v, i) {
              return mkCard(v, i, false);
            })
            .join('') +
          '</div>';
      }
      if (hid.length) {
        htmlHidden +=
          '<div class="video-category">' +
          '<h3 class="video-category-title">' +
          secTitle +
          '</h3>' +
          hid
            .map(function (v, i) {
              return mkCard(v, i, true);
            })
            .join('') +
          '</div>';
      }
    });

    grid.innerHTML = htmlVisible;

    if (htmlHidden) {
      var showMoreTxt = t['vid.showMore'] || '+ Show More Videos';
      more.innerHTML =
        htmlHidden +
        '<div style="text-align:center;margin-top:20px">' +
        '<button type="button" class="btn-secondary" id="moreBtn" onclick="toggleMore()">' +
        showMoreTxt.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;') +
        '</button>' +
        '</div>';
    } else {
      more.innerHTML = '';
    }

    document.querySelectorAll('#videoGrid .reveal, #videoMore .reveal').forEach(function (el) {
      var ob = new IntersectionObserver(
        function (entries) {
          entries.forEach(function (en) {
            if (en.isIntersecting) {
              en.target.classList.add('visible');
              ob.unobserve(en.target);
            }
          });
        },
        { threshold: 0.08, rootMargin: '0px 0px -20px 0px' }
      );
      ob.observe(el);
    });
  }

  function toggleMore() {
    var more = document.getElementById('videoMore');
    var btn = document.getElementById('moreBtn');
    if (!more) return;
    var cards = more.querySelectorAll('.video-card');
    var isHidden = cards[0] && cards[0].style.display === 'none';
    cards.forEach(function (el) {
      el.style.display = isHidden ? '' : 'none';
      if (isHidden) el.classList.add('visible');
    });
    var t = uiTable(currentLang);
    if (btn)
      btn.textContent = isHidden
        ? t['vid.showLess'] || '\u2212 Show Less'
        : t['vid.showMore'] || '+ Show More Videos';
  }

  function playVideo(videoId, ev) {
    var wrap = document.getElementById('vwrap-' + videoId);
    if (!wrap) return;
    var youtubeUrl = 'https://www.youtube.com/watch?v=' + encodeURIComponent(videoId);

    if (window.innerWidth < 768) {
      if (ev && typeof ev.preventDefault === 'function') ev.preventDefault();
      if (ev && typeof ev.stopPropagation === 'function') ev.stopPropagation();
      openVideoModal(videoId);
      return;
    }

    if (location.protocol === 'file:') {
      window.open(youtubeUrl, '_blank', 'noopener,noreferrer');
      return;
    }

    document.querySelectorAll('.video-thumb-wrap[data-playing="1"]').forEach(function (el) {
      var openId = el.id && el.id.indexOf('vwrap-') === 0 ? el.id.slice(6) : null;
      if (openId && openId !== videoId) {
        stopVideo(openId);
      }
    });
    if (wrap.dataset.playing === '1') return;

    wrap.style.cursor = 'default';
    if (!wrap.dataset.original) {
      wrap.dataset.original = wrap.innerHTML;
    }
    wrap.dataset.playing = '1';
    var L = currentLang || 'en';
    var _closeEmbed = String(effectiveUiText(L, 'ui.closeEmbed') || '\u00d7 Close')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;');
    var _closeVideoAria = String(effectiveUiText(L, 'ui.closeVideoAria') || 'Close video')
      .replace(/&/g, '&amp;')
      .replace(/"/g, '&quot;');
    var _vfbOp = String(effectiveUiText(L, 'vid.embedUnavailable') || 'Video player unavailable')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;');
    var _vfbYt = String(effectiveUiText(L, 'vid.openYoutube') || 'Open on YouTube')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;');
    wrap.innerHTML =
      '<div class="video-embed-shell" style="position:absolute;inset:0;width:100%;height:100%;">' +
      '<iframe src="https://www.youtube.com/embed/' +
      videoId +
      '?autoplay=1&rel=0&modestbranding=1"' +
      ' frameborder="0"' +
      ' allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"' +
      ' allowfullscreen' +
      ' style="position:absolute;inset:0;width:100%;height:100%"></iframe>' +
      '<button type="button" class="video-embed-close" onclick="stopVideo(\'' +
      videoId +
      '\')" aria-label="' +
      _closeVideoAria +
      '">' +
      _closeEmbed +
      '</button>' +
      '<div class="video-embed-fallback" data-yt-id="' +
      videoId +
      '" style="display:none">' +
      '<span class="vfb-op">' +
      _vfbOp +
      '</span>' +
      '<button type="button" class="btn-secondary" style="margin-top:6px" onclick="window.open(\'' +
      youtubeUrl +
      '\',\'_blank\',\'noopener\')">' +
      _vfbYt +
      '</button>' +
      '</div>' +
      '</div>';

    try {
      var iframe = wrap.querySelector('iframe');
      var fb = wrap.querySelector('.video-embed-fallback');
      if (!iframe || !fb) return;

      var markLoaded = function () {
        iframe.dataset.loaded = '1';
      };
      iframe.addEventListener('load', markLoaded);
      iframe.addEventListener('error', function () {
        iframe.remove();
        fb.style.display = 'flex';
      });

      setTimeout(function () {
        if (!iframe.dataset.loaded) {
          try {
            iframe.remove();
          } catch (e) {}
          fb.style.display = 'flex';
        }
      }, 6000);
    } catch (e) {
      var fb2 = wrap.querySelector('.video-embed-fallback');
      if (fb2) {
        var ifr = wrap.querySelector('iframe');
        if (ifr)
          try {
            ifr.remove();
          } catch (_) {}
        fb2.style.display = 'flex';
      }
    }
  }

  function openVideoModal(videoId) {
    var modal = document.getElementById('videoModal');
    var frame = document.getElementById('videoModalFrame');
    if (!modal || !frame) return;
    var youtubeUrl = 'https://www.youtube.com/watch?v=' + encodeURIComponent(videoId);

    var L = currentLang || 'en';
    var _vfbOp = String(effectiveUiText(L, 'vid.embedUnavailable') || 'Video player unavailable')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;');
    var _vfbYt = String(effectiveUiText(L, 'vid.openYoutube') || 'Open on YouTube')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;');

    var embedBase = 'https://www.youtube.com/embed/' + encodeURIComponent(videoId);
    var embedQs = 'autoplay=1&playsinline=1&rel=0&modestbranding=1';

    modal.classList.add('open');
    document.body.style.overflow = 'hidden';

    frame.innerHTML =
      '<iframe src="' +
      embedBase +
      '?' +
      embedQs +
      '"' +
      ' title="YouTube video"' +
      ' frameborder="0"' +
      ' allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen"' +
      ' allowfullscreen' +
      ' style="position:absolute;inset:0;width:100%;height:100%;border:0"></iframe>' +
      '<div class="video-embed-fallback" data-yt-id="' +
      videoId +
      '" style="display:none;position:absolute;inset:0;">' +
      '<span class="vfb-op">' +
      _vfbOp +
      '</span>' +
      '<button type="button" class="btn-secondary" style="margin-top:6px" onclick="window.open(\'' +
      youtubeUrl +
      '\',\'_blank\',\'noopener\')">' +
      _vfbYt +
      '</button>' +
      '</div>';

    try {
      var iframe = frame.querySelector('iframe');
      var fb = frame.querySelector('.video-embed-fallback');
      if (!iframe || !fb) return;

      iframe.addEventListener('error', function () {
        try {
          iframe.remove();
        } catch (_) {}
        fb.style.display = 'flex';
      });
    } catch (e) {
      var fb3 = frame.querySelector('.video-embed-fallback');
      if (fb3) {
        var ifr2 = frame.querySelector('iframe');
        if (ifr2)
          try {
            ifr2.remove();
          } catch (_) {}
        fb3.style.display = 'flex';
      }
    }
  }

  function closeVideoModal() {
    var modal = document.getElementById('videoModal');
    var frame = document.getElementById('videoModalFrame');
    if (frame) frame.innerHTML = '';
    if (modal) modal.classList.remove('open');
    document.body.style.overflow = '';
  }

  function stopVideo(videoId) {
    var wrap = document.getElementById('vwrap-' + videoId);
    if (!wrap) return;
    var original = wrap.dataset.original;
    if (original) {
      wrap.innerHTML = original;
    }
    wrap.dataset.playing = '0';
    wrap.style.cursor = '';
  }

  function setActivePhotoTab(n) {
    ['studio', 'stage', 'backstage'].forEach(function (x) {
      var tab = document.getElementById('tab-' + x);
      var panel = document.getElementById('panel-' + x);
      if (tab) tab.classList.toggle('active', x === n);
      if (panel) panel.classList.toggle('active', x === n);
    });
  }

  function getActivePhotoTab() {
    var active = document.querySelector('.photo-tab.active');
    if (active && active.id) return active.id.replace('tab-', '');
    return 'studio';
  }

  function getPhotoPanelRefs(panelName) {
    if (panelName === 'stage') {
      return {
        panel: document.getElementById('panel-stage'),
        grid: document.querySelector('#panel-stage .photo-grid-3'),
        type: 't',
        itemClass: 'photo-item-s'
      };
    }
    if (panelName === 'backstage') {
      return {
        panel: document.getElementById('panel-backstage'),
        grid: document.getElementById('backstageGrid'),
        empty: document.getElementById('backstageEmpty'),
        type: 'b',
        itemClass: 'photo-item-s'
      };
    }
    return {
      panel: document.getElementById('panel-studio'),
      grid: document.querySelector('#panel-studio .photo-grid-4'),
      type: 's',
      itemClass: 'photo-item-p'
    };
  }

  var lbSet = 's';
  var lbIdx = 0;

  function lbArr(s) {
    var ph = getPhotoPaths();
    if (s === 's') return ph.s;
    if (s === 't') return ph.t;
    return ph.b;
  }

  function updateLbCaption() {
    var cap = getCaption(lbSet, lbIdx);
    var t = document.getElementById('lbCapText');
    var p = document.getElementById('lbCapPhotog');
    if (t) {
      var caption = String(cap.caption || '').trim();
      t.textContent = caption;
      t.style.display = caption ? '' : 'none';
    }
    if (p) {
      var credit = String(cap.photographer || '').trim();
      p.textContent = credit ? '\u00a9 ' + credit : '';
      p.style.display = credit ? '' : 'none';
    }
  }

  function openLb(set, idx) {
    lbSet = set;
    lbIdx = idx;
    var arr = lbArr(set);
    if (!arr || !arr.length || arr[idx] == null) return;
    var img = document.getElementById('lbImg');
    var lb = document.getElementById('lightbox');
    var ctr = document.getElementById('lbCtr');
    if (!img || !lb || !ctr) return;
    img.src = arr[idx];
    var openCap = getCaption(lbSet, lbIdx);
    var openAlt = String(openCap.alt || '').trim();
    img.alt = openAlt || 'Photo';
    ctr.textContent = idx + 1 + ' / ' + arr.length;
    lb.classList.add('open');
    document.body.style.overflow = 'hidden';
    updateLbCaption();
  }

  function closeLb() {
    var lb = document.getElementById('lightbox');
    if (lb) lb.classList.remove('open');
    document.body.style.overflow = '';
  }

  function closeLbOnBg(e) {
    if (e.target.id === 'lightbox') closeLb();
  }

  function navLb(d) {
    var arr = lbArr(lbSet);
    if (!arr.length) return;
    lbIdx = (lbIdx + d + arr.length) % arr.length;
    var img = document.getElementById('lbImg');
    var ctr = document.getElementById('lbCtr');
    if (img) img.src = arr[lbIdx];
    if (img) {
      var navCap = getCaption(lbSet, lbIdx);
      img.alt = String(navCap.alt || '').trim() || 'Photo';
    }
    if (ctr) ctr.textContent = lbIdx + 1 + ' / ' + lbArr(lbSet).length;
    updateLbCaption();
  }

  function applyPhotosChrome() {
    if (!MP_MEDIA || !MP_MEDIA.photos) return;
    var p = MP_MEDIA.photos;
    var lang = currentLang || 'en';
    var ph2 = mpPick(lang, 'mp.photos.h2', '');
    var psub = mpPick(lang, 'mp.photos.sub', '');
    var pst = mpPick(lang, 'mp.photos.studioTab', '');
    var ptt = mpPick(lang, 'mp.photos.stageTab', '');
    var pbt = mpPick(lang, 'mp.photos.backstageTab', '');
    var pbe = mpPick(lang, 'mp.photos.backstageEmpty', '');
    var h2 = document.getElementById('photosH2');
    var sub = document.getElementById('photosSub');
    if (h2) {
      var rawH2 = ph2.trim() ? ph2 : p.h2 || '';
      if (rawH2) h2.innerHTML = formatSectionTitleIfAmpersand(rawH2);
    }
    if (sub) sub.textContent = psub.trim() ? psub : p.sub != null ? p.sub : '';
    var ts = document.getElementById('tab-studio');
    var tt = document.getElementById('tab-stage');
    var tb = document.getElementById('tab-backstage');
    if (ts) ts.textContent = pst.trim() ? pst : p.studioTab || '';
    if (tt) tt.textContent = ptt.trim() ? ptt : p.stageTab || '';
    if (tb) tb.textContent = pbt.trim() ? pbt : p.backstageTab || '';
    var bem = document.getElementById('backstageEmpty');
    if (bem) bem.textContent = pbe.trim() ? pbe : p.backstageEmpty || '';
  }

  function renderPhotoGallery() {
    var ph = getPhotoPaths();
    var lang = currentLang || 'en';
    var altStudioFb = mpPick(lang, 'mp.photos.studioTab', 'Rolando Guy');
    var altStageFb = mpPick(lang, 'mp.photos.stageTab', 'On Stage');
    var altBackFb = mpPick(lang, 'mp.photos.backstageTab', 'Backstage');
    var sRefs = getPhotoPanelRefs('studio');
    var tRefs = getPhotoPanelRefs('stage');
    var bRefs = getPhotoPanelRefs('backstage');

    function renderItems(refs, items, altFallback) {
      if (!refs || !refs.grid) return;
      refs.grid.innerHTML = (items || [])
        .map(function (src, i) {
          var imgSrc = resolvePhotoSrc(src);
          var cap = getCaption(refs.type, i);
          var alt = String(cap.alt || '').trim() || altFallback;
          return (
            '<div class="photo-item ' +
            refs.itemClass +
            ' reveal rd' +
            i % 4 +
            '" onclick="openLb(\'' +
            refs.type +
            '\',' +
            i +
            ')"><img src="' +
            imgSrc +
            '" alt="' +
            alt.replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;') +
            '" loading="lazy" decoding="async"></div>'
          );
        })
        .join('');
    }

    renderItems(sRefs, ph.s, altStudioFb);
    renderItems(tRefs, ph.t, altStageFb);
    renderItems(bRefs, ph.b, altBackFb);
    if (bRefs && bRefs.empty) bRefs.empty.style.display = ph.b && ph.b.length ? 'none' : '';

    try {
      document.querySelectorAll('#photos .reveal:not(.visible)').forEach(function (el) {
        var ob = new IntersectionObserver(
          function (entries) {
            entries.forEach(function (en) {
              if (en.isIntersecting) {
                en.target.classList.add('visible');
                ob.unobserve(en.target);
              }
            });
          },
          { threshold: 0.08, rootMargin: '0px 0px -20px 0px' }
        );
        ob.observe(el);
      });
    } catch (e) {}
  }

  function switchPhotoTab(nextTab) {
    var next = nextTab || 'studio';
    setActivePhotoTab(next);
    renderPhotoGallery();
  }

  document.addEventListener('keydown', function (e) {
    var lb = document.getElementById('lightbox');
    var vm = document.getElementById('videoModal');
    if (e.key === 'Escape') {
      if (lb && lb.classList.contains('open')) {
        closeLb();
        return;
      }
      if (vm && vm.classList.contains('open')) {
        closeVideoModal();
      }
      return;
    }
    if (lb && lb.classList.contains('open')) {
      if (e.key === 'ArrowLeft') navLb(-1);
      if (e.key === 'ArrowRight') navLb(1);
    }
  });

  window.toggleMore = toggleMore;
  window.playVideo = playVideo;
  window.openVideoModal = openVideoModal;
  window.closeVideoModal = closeVideoModal;
  window.stopVideo = stopVideo;
  window.showTab = switchPhotoTab;
  window.openLb = openLb;
  window.closeLb = closeLb;
  window.closeLbOnBg = closeLbOnBg;
  window.navLb = navLb;

  window.addEventListener('mp:langchange', function (e) {
    currentLang = (e.detail && e.detail.lang) || 'en';
    if (!MP_MEDIA) return;
    applyPhotosChrome();
    renderVideos();
    setActivePhotoTab(getActivePhotoTab());
    renderPhotoGallery();
  });

  window.addEventListener('mp:localesready', function () {
    if (typeof window.getMpSiteLang === 'function') currentLang = window.getMpSiteLang();
    if (!MP_MEDIA) return;
    applyPhotosChrome();
    renderVideos();
    setActivePhotoTab(getActivePhotoTab());
    renderPhotoGallery();
  });

  fetch('/v1-assets/data/media-data.json', { cache: 'no-store' })
    .then(function (r) {
      if (!r.ok) throw new Error(r.statusText);
      return r.json();
    })
    .then(function (data) {
      MP_MEDIA = data;
      return applyLiveMediaOverridesFromFirestore();
    })
    .then(function () {
      if (typeof window.getMpSiteLang === 'function') currentLang = window.getMpSiteLang();
      applyPhotosChrome();
      renderVideos();
      setActivePhotoTab(getActivePhotoTab());
      renderPhotoGallery();
    })
    .catch(function () {
      var lang = (typeof window.getMpSiteLang === 'function' && window.getMpSiteLang()) || 'en';
      MP_MEDIA = {
        vid: {
          h2:
            mpPick(lang, 'mp.videos.h2', 'Stage, Concert &amp; <em>Recital Highlights</em>'),
          videos: []
        },
        photos: {
          h2: mpPick(lang, 'mp.photos.h2', 'Portraits, Stage &amp; <em>Backstage</em>'),
          sub: mpPick(lang, 'mp.mediaLoadError', 'Media data could not be loaded.'),
          studioTab: mpPick(lang, 'mp.photos.studioTab', 'Studio Portraits'),
          stageTab: mpPick(lang, 'mp.photos.stageTab', 'On Stage'),
          backstageTab: mpPick(lang, 'mp.photos.backstageTab', 'Backstage'),
          backstageEmpty: mpPick(lang, 'mp.photos.backstageEmpty', 'No photos yet.'),
          s: [],
          t: [],
          b: [],
          captions: {}
        }
      };
      applyPhotosChrome();
      renderVideos();
      setActivePhotoTab(getActivePhotoTab());
      renderPhotoGallery();
    });
})();
