/**
 * v1 press quotes + EPK for mp/press.html.
 * Data: /v1-assets/data/press-data.json (generated by scripts/build-press.js from admin export
 * rg_press, rg_press_meta, rg_ui_*.reviewsIntro, rg_epk_photos, rg_public_pdfs; defaults in
 * v1-assets/build/press-defaults.json) plus epk-bios.json from build-epk-bios.js.
 */
(function () {
  'use strict';
  var FIRESTORE_PROJECT_ID = 'rolandoguy-57d63';
  var PRESS_DEBUG_STATE = {
    reviewsSource: '',
    globalReviews: true,
    totalQuotes: 0,
    visibleQuotes: 0,
    photosSource: '',
    resolvedPhotos: 0,
    renderedPhotos: 0,
    candidateRows: {
      reviews: [],
      reviewsMeta: [],
      photos: []
    },
    winners: {
      reviews: '',
      reviewsMeta: '',
      photos: ''
    }
  };

  var MP_PRESS = null;
  var MP_LIVE = {
    press: null,
    pressMeta: null,
    epkPhotos: null,
    publicPdfs: null
  };
  function parseLocalJson(key) {
    try {
      if (!window.localStorage) return null;
      var raw = window.localStorage.getItem(key);
      if (!raw) return null;
      return JSON.parse(raw);
    } catch (e) {
      return null;
    }
  }
  function fetchFirestoreDocJson(key) {
    var url = 'https://firestore.googleapis.com/v1/projects/' + FIRESTORE_PROJECT_ID + '/databases/(default)/documents/rg/' + encodeURIComponent(key);
    return fetch(url, { cache: 'no-store' })
      .then(function (r) {
        if (!r.ok) return null;
        return r.json();
      })
      .then(function (doc) {
        var v = doc && doc.fields && doc.fields.value && doc.fields.value.stringValue;
        if (!v || typeof v !== 'string') return null;
        try { return JSON.parse(v); } catch (e) { return null; }
      })
      .catch(function () { return null; });
  }
  function loadLiveRuntimeOverrides() {
    return Promise.all([
      fetchFirestoreDocJson('rg_press'),
      fetchFirestoreDocJson('rg_press_meta'),
      fetchFirestoreDocJson('rg_epk_photos'),
      fetchFirestoreDocJson('rg_public_pdfs')
    ]).then(function (vals) {
      MP_LIVE = {
        press: vals[0],
        pressMeta: vals[1],
        epkPhotos: vals[2],
        publicPdfs: vals[3]
      };
      return MP_LIVE;
    }).catch(function () {
      MP_LIVE = { press: null, pressMeta: null, epkPhotos: null, publicPdfs: null };
      return MP_LIVE;
    });
  }
  function unwrapPayload(v) {
    if (v && typeof v === 'object' && v.value != null) return v.value;
    return v;
  }
  function normalizeCandidateRaw(raw) {
    var v = unwrapPayload(raw);
    // Some legacy entries keep JSON payload in string form inside value.
    if (typeof v === 'string') {
      var s = v.trim();
      if (!s) return null;
      try {
        v = JSON.parse(s);
        v = unwrapPayload(v);
      } catch (e) {}
    }
    return v;
  }
  function normalizePressItems(raw) {
    var src = normalizeCandidateRaw(raw);
    if (Array.isArray(src)) return src;
    if (src && typeof src === 'object' && Array.isArray(src.items)) return src.items;
    if (src && typeof src === 'object') {
      var numericKeys = Object.keys(src).filter(function (k) { return /^\d+$/.test(k); }).sort(function (a, b) { return Number(a) - Number(b); });
      if (numericKeys.length) return numericKeys.map(function (k) { return src[k]; });
    }
    return [];
  }
  function normalizePressMeta(raw) {
    var src = normalizeCandidateRaw(raw);
    return src && typeof src === 'object' ? src : {};
  }
  function asVisibleFlag(raw, fb) {
    if (raw === false || raw === 'false' || raw === 0 || raw === '0' || raw === '' || raw == null) return false;
    if (raw === true || raw === 'true' || raw === 1 || raw === '1') return true;
    return fb;
  }
  function renderPressDebugLine() {}
  function readLegacyJson(key) {
    try {
      var unwrap = function (v) {
        if (v && typeof v === 'object' && v.value != null) return v.value;
        return v;
      };
      var scorePublicPdfs = function (v) {
        if (!v || typeof v !== 'object') return 0;
        var score = 0;
        ['dossier', 'artistSheet'].forEach(function (kind) {
          var block = v[kind];
          if (!block || typeof block !== 'object') return;
          Object.keys(block).forEach(function (k) {
            var e = block[k];
            if (typeof e === 'string' && e.trim()) score++;
            else if (e && typeof e === 'object') {
              if (typeof e.url === 'string' && e.url.trim()) score++;
              else if (typeof e.data === 'string' && e.data.trim()) score++;
            }
          });
        });
        return score;
      };
      // Direct legacy key (older behavior / manual writes).
      var direct = normalizeCandidateRaw(unwrap(parseLocalJson(key)));
      // Admin fallback key used by admin.html save(): rg_local_<key> with { ts, value } envelope.
      var wrapped = normalizeCandidateRaw(unwrap(parseLocalJson('rg_local_' + key)));
      if (key === 'rg_epk_photos') {
        var directLen = countNormalizedEpkPhotos(direct);
        var wrappedLen = countNormalizedEpkPhotos(wrapped);
        return wrappedLen > directLen ? wrapped : direct;
      }
      if (key === 'rg_public_pdfs') {
        var dScore = scorePublicPdfs(direct);
        var wScore = scorePublicPdfs(wrapped);
        return wScore > dScore ? wrapped : direct;
      }
      return direct != null ? direct : wrapped;
    } catch (e) {
      return null;
    }
  }

  function mpPick(lang, key, fb) {
    var p = window.pickMpLocaleString;
    if (p) {
      var v = p(lang, key);
      if (v != null && String(v).trim() !== '') return v;
    }
    return fb;
  }

  function mpUiTable(lang, defaults) {
    var t = {};
    for (var k in defaults) {
      if (Object.prototype.hasOwnProperty.call(defaults, k)) t[k] = mpPick(lang, k, defaults[k]);
    }
    return t;
  }
  /** @type {Record<string, { b50: string, b150: string, b300p1: string, b300p2: string, b300p3: string, b300p4: string }>|null} */
  var EPK_BIOS_POOL = null;
  var currentLang = 'en';
  var epkActiveBio = 'bio150';

  var LANGS = ['en', 'de', 'es', 'it', 'fr'];
  var EPK_FIELDS = ['b50', 'b150', 'b300p1', 'b300p2', 'b300p3', 'b300p4'];

  function normalizeEpkBiosPayload(obj) {
    var out = {};
    LANGS.forEach(function (lang) {
      var src = obj && typeof obj === 'object' ? obj[lang] : null;
      var o = {};
      EPK_FIELDS.forEach(function (f) {
        o[f] = src && typeof src[f] === 'string' ? src[f] : '';
      });
      out[lang] = o;
    });
    return out;
  }

  function emptyEpkBiosPool() {
    return normalizeEpkBiosPayload(null);
  }

  var MP_PRESS_UI_EN = {
    'press.tag': 'Press coverage',
    'press.empty': 'No press quotes yet.',
    'press.readMore': 'Read article',
    'epk.tag': 'Presenter materials',
    'epk.title': 'Dossier',
    'epk.bio50lbl': '50-word Bio',
    'epk.bio150lbl': '150-word Bio',
    'epk.bio300lbl': 'Full Biography',
    'epk.copyBio': '\u29d6 Copy biography',
    'epk.photos': 'High-Res Photos',
    'epk.photosIntro':
      'Official press images for media, programmes and print use. Please credit the photographer where indicated.',
    'epk.photoCredit': 'Press and programme photos. Photo credits indicated per image.',
    'epk.docs': 'Documents',
    'epk.downloadDossier': 'Download dossier',
    'epk.downloadArtistSheet': 'Download artist sheet',
    'epk.programsLink': 'See programmes and artistic collaborations',
    'epk.downloadPhoto': 'Download hi-res',
    'epk.preview': 'Preview',
    'epk.pdfSoon': 'Available soon',
    'ui.copied': '\u2713 Copied!'
  };

  function uiTable(lang) {
    var L = lang || currentLang || 'en';
    return mpUiTable(L, MP_PRESS_UI_EN);
  }

  function effectiveUiText(lang, key) {
    var L = lang || currentLang || 'en';
    return mpPick(L, key, MP_PRESS_UI_EN[key]);
  }

  var PUBLIC_PDF_DEFAULTS = {
    dossier: { EN: { url: '', data: '' }, DE: { url: '', data: '' }, ES: { url: '', data: '' }, IT: { url: '', data: '' }, FR: { url: '', data: '' } },
    artistSheet: { EN: { url: '', data: '' }, DE: { url: '', data: '' }, ES: { url: '', data: '' }, IT: { url: '', data: '' }, FR: { url: '', data: '' } }
  };

  function getPublicPdfs() {
    var raw = MP_PRESS && MP_PRESS.publicPdfs;
    var live = MP_LIVE && MP_LIVE.publicPdfs;
    var legacy = readLegacyJson('rg_public_pdfs');
    var out = JSON.parse(JSON.stringify(PUBLIC_PDF_DEFAULTS));
    var langs = ['EN', 'DE', 'ES', 'IT', 'FR'];
    var langSet = { EN: true, DE: true, ES: true, IT: true, FR: true };
    var normalizeLangKey = function (key) {
      var k = String(key || '').trim();
      if (!k) return '';
      var short = k.split('-')[0].toUpperCase();
      return langSet[short] ? short : '';
    };
    var assignEntry = function (kind, langKey, v) {
      if (!langKey) return;
      if (typeof v === 'string') {
        var s = v.trim();
        if (!s) return;
        if (/^data:application\/pdf/i.test(s)) out[kind][langKey].data = s;
        else out[kind][langKey].url = s;
        return;
      }
      if (v && typeof v === 'object') {
        if (typeof v.url === 'string') {
          var u = v.url.trim();
          if (u) out[kind][langKey].url = u;
        }
        if (typeof v.data === 'string') {
          var d = v.data.trim();
          if (d) out[kind][langKey].data = d;
        }
        if (v.value && typeof v.value === 'object') {
          if (typeof v.value.url === 'string') {
            var u2 = v.value.url.trim();
            if (u2) out[kind][langKey].url = u2;
          }
          if (typeof v.value.data === 'string') {
            var d2 = v.value.data.trim();
            if (d2) out[kind][langKey].data = d2;
          }
        }
      }
    };
    var mergeFrom = function (srcRoot) {
      if (!srcRoot || typeof srcRoot !== 'object') return;
      ['dossier', 'artistSheet'].forEach(function (kind) {
        var src = srcRoot[kind];
        if (!src || typeof src !== 'object') return;
        Object.keys(src).forEach(function (key) {
          var L = normalizeLangKey(key);
          if (!L) return;
          assignEntry(kind, L, src[key]);
        });
        // Also accept nested block wrappers if present.
        if (src.value && typeof src.value === 'object') {
          Object.keys(src.value).forEach(function (key) {
            var L = normalizeLangKey(key);
            if (!L) return;
            assignEntry(kind, L, src.value[key]);
          });
        }
      });
    };
    // Base snapshot first, then live admin/localStorage overrides.
    mergeFrom(raw);
    mergeFrom(live);
    mergeFrom(legacy);
    return out;
  }

  function getPress() {
    var raw = MP_PRESS && MP_PRESS.press;
    return Array.isArray(raw) ? raw : [];
  }

  function getPressMetaFrom(rawMeta) {
    var fallback = {
      en: { translatedNote: 'Translated from the original German review.' },
      de: { translatedNote: '' },
      es: { translatedNote: 'Traducción de la reseña original en alemán.' },
      it: { translatedNote: 'Traduzione dalla recensione originale in tedesco.' },
      fr: { translatedNote: 'Traduction de la critique originale en allemand.' }
    };
    var src = (rawMeta && typeof rawMeta === 'object') ? rawMeta : {};
    if (!src || typeof src !== 'object') return JSON.parse(JSON.stringify(fallback));
    var out = JSON.parse(JSON.stringify(fallback));
    ['en', 'de', 'es', 'it', 'fr'].forEach(function (l) {
      if (src[l] && typeof src[l].translatedNote === 'string') out[l].translatedNote = src[l].translatedNote;
    });
    out.showReviewsSection = asVisibleFlag(src.showReviewsSection, true);
    return out;
  }

  function asVisibleFlag(raw, fb) {
    if (raw === false || raw === 'false' || raw === 0 || raw === '0') return false;
    if (raw === true || raw === 'true' || raw === 1 || raw === '1') return true;
    return fb;
  }

  function normalizeEpkPhotos(raw) {
    var src = normalizeCandidateRaw(raw);
    if (!Array.isArray(src) && src && typeof src === 'object' && Array.isArray(src.value)) src = src.value;
    if (!Array.isArray(src) && src && typeof src === 'object' && Array.isArray(src.photos)) src = src.photos;
    if (!Array.isArray(src) && src && typeof src === 'object') {
      var numericKeys = Object.keys(src).filter(function (k) { return /^\d+$/.test(k); }).sort(function (a, b) { return Number(a) - Number(b); });
      if (numericKeys.length) src = numericKeys.map(function (k) { return src[k]; });
    }
    var normalizePhotoUrl = function (u) {
      var s = String(u || '').trim();
      if (!s) return '';
      if (/^(data:|https?:\/\/|\/\/|\/|\.\.\/)/i.test(s)) return s;
      if (/^\.\//.test(s)) s = s.slice(2);
      if (/^img\//i.test(s)) return '../' + s;
      return '../img/' + s;
    };
    var arr = Array.isArray(src) ? src : [];
    return arr
      .map(function (ph) {
        if (typeof ph === 'string') return { url: normalizePhotoUrl(ph), caption: '', alt: '', photographer: '', label: '', credit: '' };
        if (!ph || typeof ph !== 'object') return null;
        var caption = typeof ph.caption === 'string' ? ph.caption : (typeof ph.label === 'string' ? ph.label : '');
        var photographer = typeof ph.photographer === 'string' ? ph.photographer : (typeof ph.credit === 'string' ? ph.credit : '');
        return {
          url: normalizePhotoUrl(typeof ph.url === 'string' ? ph.url : ''),
          caption: caption,
          alt: typeof ph.alt === 'string' ? ph.alt : '',
          photographer: photographer,
          label: caption,
          credit: photographer
        };
      })
      .filter(function (ph) { return ph && ph.url; });
  }
  function countNormalizedEpkPhotos(raw) {
    return normalizeEpkPhotos(raw).length;
  }
  function scorePressItems(raw) {
    if (!Array.isArray(raw)) return 0;
    return raw.filter(function (p) {
      if (!p || typeof p !== 'object') return false;
      var q = typeof p.quote === 'string' ? p.quote.trim() : '';
      var src = typeof p.source === 'string' ? p.source.trim() : '';
      return !!(q || src);
    }).length;
  }
  function scorePressMeta(raw) {
    if (!raw || typeof raw !== 'object') return 0;
    var score = 0;
    if (raw.showReviewsSection != null) score += 10;
    ['en', 'de', 'es', 'it', 'fr'].forEach(function (l) {
      if (raw[l] && typeof raw[l].translatedNote === 'string' && raw[l].translatedNote.trim()) score += 1;
    });
    return score;
  }
  function resolveBestSource(name, candidates, scorer, normalizer) {
    var sourcePriority = function (sourceName) {
      // Prefer runtime/local admin sources over static press-data on ties.
      if (/^local:rg_local_/i.test(sourceName)) return 60;
      if (/^local:rg_/i.test(sourceName)) return 55;
      if (/^firestore:/i.test(sourceName)) return 53;
      if (/^readLegacyJson\(/i.test(sourceName)) return 50;
      if (/^press-data:/i.test(sourceName)) return 10;
      return 0;
    };
    var scored = candidates.map(function (c) {
      var normalizedRaw = normalizeCandidateRaw(c.raw);
      var normalized = normalizer ? normalizer(normalizedRaw) : normalizedRaw;
      var score = scorer(normalized);
      return {
        source: c.name,
        raw: normalizedRaw,
        found: normalizedRaw != null,
        rawType: Array.isArray(normalizedRaw) ? 'array' : typeof normalizedRaw,
        rawLength: Array.isArray(normalizedRaw) ? normalizedRaw.length : null,
        normalized: normalized,
        score: score,
        priority: sourcePriority(c.name)
      };
    });
    var best = scored[0];
    for (var i = 1; i < scored.length; i++) {
      if (scored[i].score > best.score) best = scored[i];
      else if (scored[i].score === best.score && scored[i].priority > best.priority) best = scored[i];
    }
    if (name === 'reviews' || name === 'reviewsMeta' || name === 'photos') {
      PRESS_DEBUG_STATE.candidateRows[name] = scored.map(function (s) {
        return {
          source: s.source,
          score: s.score,
          found: s.found,
          rawType: s.rawType,
          rawLength: s.rawLength
        };
      });
      PRESS_DEBUG_STATE.winners[name] = best.source;
    }
    return best;
  }
  function resolvePressRuntime() {
    var staticPress = (MP_PRESS && Array.isArray(MP_PRESS.press)) ? MP_PRESS.press : [];
    var staticMeta = (MP_PRESS && MP_PRESS.pressMeta && typeof MP_PRESS.pressMeta === 'object') ? MP_PRESS.pressMeta : {};
    var livePress = MP_LIVE && MP_LIVE.press;
    var liveMeta = MP_LIVE && MP_LIVE.pressMeta;
    var directPress = parseLocalJson('rg_press');
    var wrappedPress = parseLocalJson('rg_local_rg_press');
    var directMeta = parseLocalJson('rg_press_meta');
    var wrappedMeta = parseLocalJson('rg_local_rg_press_meta');

    var pressBest = resolveBestSource(
      'reviews',
      [
        { name: 'local:rg_press', raw: directPress },
        { name: 'local:rg_press.unwrapped', raw: unwrapPayload(directPress) },
        { name: 'local:rg_local_rg_press', raw: wrappedPress },
        { name: 'local:rg_local_rg_press.unwrapped', raw: unwrapPayload(wrappedPress) },
        { name: 'readLegacyJson(rg_press)', raw: readLegacyJson('rg_press') },
        { name: 'firestore:rg_press', raw: livePress },
        { name: 'press-data:press', raw: staticPress }
      ],
      function (arr) { return scorePressItems(arr); },
      function (raw) { return normalizePressItems(raw); }
    );
    var metaBest = resolveBestSource(
      'reviewsMeta',
      [
        { name: 'local:rg_press_meta', raw: directMeta },
        { name: 'local:rg_press_meta.unwrapped', raw: unwrapPayload(directMeta) },
        { name: 'local:rg_local_rg_press_meta', raw: wrappedMeta },
        { name: 'local:rg_local_rg_press_meta.unwrapped', raw: unwrapPayload(wrappedMeta) },
        { name: 'readLegacyJson(rg_press_meta)', raw: readLegacyJson('rg_press_meta') },
        { name: 'firestore:rg_press_meta', raw: liveMeta },
        { name: 'press-data:pressMeta', raw: staticMeta }
      ],
      function (obj) { return scorePressMeta(obj); },
      function (raw) { return normalizePressMeta(raw); }
    );

    return {
      pressSource: pressBest.source,
      metaSource: metaBest.source,
      pressItems: pressBest.normalized,
      pressMeta: getPressMetaFrom(metaBest.normalized)
    };
  }
  function resolveEpkPhotosSource() {
    var candidates = [];
    var addCandidate = function (name, raw) {
      var normalized = normalizeEpkPhotos(raw);
      candidates.push({
        name: name,
        raw: raw,
        rawType: Array.isArray(raw) ? 'array' : typeof raw,
        rawLength: Array.isArray(raw) ? raw.length : null,
        validCount: normalized.length,
        normalized: normalized
      });
    };
    var parseMaybe = function (raw) {
      if (!raw) return null;
      try { return JSON.parse(raw); } catch (e) { return null; }
    };
    var unwrapMaybe = function (obj) {
      if (obj && typeof obj === 'object' && obj.value != null) return obj.value;
      return obj;
    };

    var directRaw = parseMaybe(window.localStorage && window.localStorage.getItem('rg_epk_photos'));
    var wrappedRaw = parseMaybe(window.localStorage && window.localStorage.getItem('rg_local_rg_epk_photos'));
    var readLegacy = readLegacyJson('rg_epk_photos');
    var liveRaw = MP_LIVE && MP_LIVE.epkPhotos;
    var staticRaw = (MP_PRESS && MP_PRESS.epkPhotos) || [];

    addCandidate('local:rg_epk_photos', directRaw);
    addCandidate('local:rg_epk_photos.unwrapped', unwrapMaybe(directRaw));
    addCandidate('local:rg_local_rg_epk_photos', wrappedRaw);
    addCandidate('local:rg_local_rg_epk_photos.unwrapped', unwrapMaybe(wrappedRaw));
    addCandidate('readLegacyJson(rg_epk_photos)', readLegacy);
    addCandidate('firestore:rg_epk_photos', liveRaw);
    addCandidate('press-data:epkPhotos', staticRaw);

    var bestWrapped = resolveBestSource(
      'photos',
      candidates.map(function (c) { return { name: c.name, raw: c.raw }; }),
      function (arr) { return Array.isArray(arr) ? arr.length : 0; },
      function (raw) { return normalizeEpkPhotos(raw); }
    );
    return {
      sourceName: bestWrapped.source,
      photos: bestWrapped.normalized,
      allCandidates: candidates
    };
  }

  function getDefaultEpkBios() {
    if (EPK_BIOS_POOL && typeof EPK_BIOS_POOL === 'object') return EPK_BIOS_POOL;
    return emptyEpkBiosPool();
  }

  function renderPress() {
    var resolved = resolvePressRuntime();
    var pressSection = document.getElementById('press');
    var meta = resolved.pressMeta;
    var showReviewsRaw = meta && meta.showReviewsSection;
    var showReviews = asVisibleFlag(showReviewsRaw, true);
    if (pressSection) pressSection.style.display = showReviews ? '' : 'none';
    var allQuotes = resolved.pressItems;
    var visibleQuotes = allQuotes.filter(function (p) { return asVisibleFlag(p && p.visible, true); });
    if (!showReviews) return;
    var el = document.getElementById('pressGrid');
    if (!el) return;
    var items = visibleQuotes
      .sort(function (a, b) {
        return (a.order || 0) - (b.order || 0);
      });
    var lang = currentLang || 'en';
    var pickLang = function (obj, baseKey) {
      if (!obj || typeof obj !== 'object') return '';
      var i18nMap = obj[baseKey + '_i18n'];
      if (i18nMap && typeof i18nMap === 'object') {
        return i18nMap[lang] || i18nMap.en || (typeof obj[baseKey] === 'string' ? obj[baseKey] : '');
      }
      var langField = obj[baseKey + '_' + lang];
      if (typeof langField === 'string' && langField.trim()) return langField;
      var enField = obj[baseKey + '_en'];
      if (typeof enField === 'string' && enField.trim()) return enField;
      var baseVal = obj[baseKey];
      return typeof baseVal === 'string' ? baseVal : '';
    };
    var pressMeta = meta;
    var translatedNote = (((pressMeta[lang] || {}).translatedNote) || '').trim();
    var ensureProdI18n = function (p) {
      var base =
        p && typeof p.production === 'string' && p.production.trim()
          ? p.production
          : '';
      var map = p && p.production_i18n && typeof p.production_i18n === 'object' ? p.production_i18n : {};
      return {
        en:
          typeof map.en === 'string' && map.en.trim()
            ? map.en
            : base,
        de: typeof map.de === 'string' && map.de.trim() ? map.de : '',
        es: typeof map.es === 'string' && map.es.trim() ? map.es : '',
        it: typeof map.it === 'string' && map.it.trim() ? map.it : '',
        fr: typeof map.fr === 'string' && map.fr.trim() ? map.fr : ''
      };
    };
    if (!items.length) {
      el.innerHTML =
        '<div class="press-empty">' +
        (effectiveUiText(lang, 'press.empty') || 'No press quotes yet.') +
        '</div>';
      return;
    }
    el.innerHTML = items
      .map(function (p) {
        var quoteBlock = (function () {
          var original = typeof p.quote === 'string' ? p.quote.trim() : '';
          var qmap = p && p.quotes_i18n && typeof p.quotes_i18n === 'object' ? p.quotes_i18n : {};
          var shown = original;
          var usedTranslation = false;
          if (lang !== 'de') {
            var tQuote =
              typeof qmap[lang] === 'string' && qmap[lang].trim()
                ? qmap[lang].trim()
                : typeof qmap.en === 'string' && qmap.en.trim()
                  ? qmap.en.trim()
                  : '';
            if (tQuote) {
              shown = tQuote;
              usedTranslation = !!(original && tQuote !== original);
            }
          }
          if (!shown) shown = pickLang(p, 'quote') || '';
          return (
            shown +
            (lang !== 'de' && usedTranslation && translatedNote
              ? '<div style="margin-top:8px;font-size:.66rem;color:var(--text-faint);line-height:1.5;font-style:italic">' +
                translatedNote +
                '</div>'
              : '')
          );
        })();
        var prodPick = pickLang(Object.assign({}, p, { production_i18n: ensureProdI18n(p) }), 'production');
        var readMore = effectiveUiText(lang, 'press.readMore') || 'Read article';
        return (
          '<div class="press-card">' +
          '<div class="press-source">' +
          (p.source || '') +
          '</div>' +
          '<div class="press-quote">' +
          quoteBlock +
          '</div>' +
          '<div class="press-production">' +
          prodPick +
          '</div>' +
          (p.url
            ? '<a href="' +
              p.url +
              '" target="_blank" rel="noopener" style="font-family:var(--ff-caps);font-size:.48rem;letter-spacing:.15em;color:var(--gold-dim);text-decoration:none;margin-top:12px;display:inline-block;transition:color .3s" onmouseover="this.style.color=\'var(--gold)\'" onmouseout="this.style.color=\'var(--gold-dim)\'">' +
              readMore +
              ' \u2197</a>'
            : '') +
          '</div>'
        );
      })
      .join('');
  }

  function epkTab(btn, pane) {
    document.querySelectorAll('.epk-tab').forEach(function (b) {
      b.classList.remove('active');
    });
    document.querySelectorAll('.epk-bio-pane').forEach(function (p) {
      p.classList.remove('active');
    });
    btn.classList.add('active');
    var pan = document.getElementById(pane);
    if (pan) pan.classList.add('active');
    epkActiveBio = pane;
  }

  function epkCopyBio() {
    var lang = currentLang || 'en';
    var pool = getDefaultEpkBios();
    var bios = pool[lang] || pool.en;
    if (!bios) return;
    var text = '';
    if (epkActiveBio === 'bio50') text = bios.b50 || '';
    else if (epkActiveBio === 'bio150') text = bios.b150 || '';
    else text = [bios.b300p1, bios.b300p2, bios.b300p3, bios.b300p4].filter(Boolean).join('\n\n');
    var btn = document.getElementById('epkCopyBtn');
    var fallbackCopied = effectiveUiText(lang, 'ui.copied') || '\u2713 Copied!';
    function flashCopied() {
      if (!btn) return;
      var prev = btn.textContent;
      btn.textContent = fallbackCopied;
      setTimeout(function () {
        btn.textContent = prev;
      }, 2000);
    }
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).then(flashCopied).catch(function () {});
    }
  }

  function renderEpk() {
    var lang = currentLang || 'en';
    var pool = getDefaultEpkBios();
    var bios = pool[lang] || pool.en || { b50: '', b150: '', b300p1: '', b300p2: '', b300p3: '', b300p4: '' };
    var ti = uiTable(lang);

    var titleEl = document.getElementById('epkTitle');
    if (titleEl) titleEl.innerHTML = ti['epk.title'] || 'Dossier';

    document.querySelectorAll('.epk-tab').forEach(function (btn, i) {
      var keys = ['epk.bio50lbl', 'epk.bio150lbl', 'epk.bio300lbl'];
      if (ti[keys[i]]) btn.textContent = ti[keys[i]];
    });

    var storedBios =
      (MP_PRESS && MP_PRESS.epkBiosOverrides && MP_PRESS.epkBiosOverrides[lang]) || {};
    var activeBios = {
      b50: storedBios.b50 || bios.b50 || '',
      b150: storedBios.b150 || bios.b150 || '',
      b300p1: storedBios.b300p1 || bios.b300p1 || '',
      b300p2: storedBios.b300p2 || bios.b300p2 || '',
      b300p3: storedBios.b300p3 || bios.b300p3 || '',
      b300p4: storedBios.b300p4 || bios.b300p4 || ''
    };
    var b50el = document.getElementById('bio50Text');
    var b150el = document.getElementById('bio150Text');
    if (b50el) b50el.textContent = activeBios.b50;
    if (b150el) b150el.textContent = activeBios.b150;
    var p1 = document.getElementById('bio300TextP1');
    var p2 = document.getElementById('bio300TextP2');
    var p3 = document.getElementById('bio300TextP3');
    var p4 = document.getElementById('bio300TextP4');
    if (p1) p1.textContent = activeBios.b300p1;
    if (p2) p2.textContent = activeBios.b300p2;
    if (p3) p3.textContent = activeBios.b300p3;
    if (p4) p4.textContent = activeBios.b300p4;

    var epkLblPhotos = document.getElementById('epkLblPhotos');
    var epkPhotosIntroEl = document.getElementById('epkPhotosIntro');
    var epkPhotoNoteEl = document.getElementById('epkPhotoNote');
    var epkLblDocs = document.getElementById('epkLblDocs');
    if (epkLblPhotos && ti['epk.photos']) epkLblPhotos.textContent = ti['epk.photos'];
    if (epkPhotosIntroEl && ti['epk.photosIntro']) epkPhotosIntroEl.textContent = ti['epk.photosIntro'];
    if (epkPhotoNoteEl && ti['epk.photoCredit']) epkPhotoNoteEl.textContent = ti['epk.photoCredit'];
    if (epkLblDocs && ti['epk.docs']) epkLblDocs.textContent = ti['epk.docs'];
    var dossierBtnLabel = document.getElementById('epkDossierBtn');
    var artistBtnLabel = document.getElementById('epkArtistSheetBtn');
    if (dossierBtnLabel && ti['epk.downloadDossier']) dossierBtnLabel.textContent = ti['epk.downloadDossier'];
    if (artistBtnLabel && ti['epk.downloadArtistSheet']) artistBtnLabel.textContent = ti['epk.downloadArtistSheet'];

    var sourceResolution = resolveEpkPhotosSource();
    var epkPhotos = sourceResolution.photos;
    var chosenSourceName = sourceResolution.sourceName;
    var photosContainer = document.getElementById('epkPhotosGrid');
    if (photosContainer) {
      var childCountBefore = photosContainer.children ? photosContainer.children.length : 0;
      if (!epkPhotos.length) {
        photosContainer.innerHTML = '';
      } else {
        var t = uiTable(currentLang);
        var downloadLbl = (t['epk.downloadPhoto'] || 'Download hi-res')
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;');
        var previewLbl = (t['epk.preview'] || 'Preview')
          .replace(/&/g, '&amp;')
          .replace(/</g, '&lt;')
          .replace(/>/g, '&gt;')
          .replace(/"/g, '&quot;');
        var validPhotos = epkPhotos.filter(function (ph) {
          return ph && typeof ph.url === 'string' && ph.url.trim();
        });
        photosContainer.innerHTML = '';
        var frag = document.createDocumentFragment();
        validPhotos.forEach(function (ph, i) {
          var url = String(ph.url || '').trim();
          var caption = String((ph.caption || ph.label || '').trim());
          var photographer = String((ph.photographer || ph.credit || '').trim());
          var alt = String((ph.alt || '').trim()) || caption || photographer || 'Press photo — Rolando Guy';

          var card = document.createElement('article');
          card.className = 'epk-press-card';

          var frame = document.createElement('div');
          frame.className = 'epk-press-frame';
          var img = document.createElement('img');
          img.src = url;
          img.alt = alt;
          img.loading = 'lazy';
          frame.appendChild(img);

          var body = document.createElement('div');
          body.className = 'epk-press-body';
          if (caption) {
            var labelEl = document.createElement('span');
            labelEl.className = 'epk-press-label';
            labelEl.textContent = caption;
            body.appendChild(labelEl);
          }

          if (photographer) {
            var creditEl = document.createElement('p');
            creditEl.className = 'epk-press-credit';
            creditEl.textContent = photographer;
            body.appendChild(creditEl);
          }

          var actions = document.createElement('div');
          actions.className = 'epk-press-actions';
          var preview = document.createElement('a');
          preview.href = url;
          preview.target = '_blank';
          preview.rel = 'noopener';
          preview.className = 'epk-press-preview';
          preview.textContent = previewLbl;
          var dl = document.createElement('a');
          dl.href = url;
          dl.setAttribute('download', '');
          dl.className = 'epk-press-dl';
          dl.textContent = downloadLbl;
          actions.appendChild(preview);
          actions.appendChild(dl);

          body.appendChild(actions);
          card.appendChild(frame);
          card.appendChild(body);
          frag.appendChild(card);

        });
        photosContainer.appendChild(frag);
      }
      var cardCount = photosContainer.querySelectorAll('.epk-press-card').length;
      var imgNodes = photosContainer.querySelectorAll('img');
      var usableSrcCount = 0;
      imgNodes.forEach(function (n) {
        if (String(n.getAttribute('src') || '').trim()) usableSrcCount++;
      });
    }

    var pdfs = getPublicPdfs();
    var normalizePdfValue = function (entry) {
      if (typeof entry === 'string') return entry.trim();
      if (!entry || typeof entry !== 'object') return '';
      if (typeof entry.url === 'string' && entry.url.trim()) return entry.url.trim();
      if (typeof entry.data === 'string' && entry.data.trim()) return entry.data.trim();
      if (entry.value && typeof entry.value === 'object') {
        if (typeof entry.value.url === 'string' && entry.value.url.trim()) return entry.value.url.trim();
        if (typeof entry.value.data === 'string' && entry.value.data.trim()) return entry.value.data.trim();
      }
      return '';
    };
    var isConfiguredPdf = function (url) {
      var u = String(url || '').trim();
      if (!u) return false;
      if (/^(#|javascript:|about:blank)$/i.test(u)) return false;
      if (/placeholder|todo|coming[-_\s]?soon/i.test(u)) return false;
      return true;
    };
    var langToPdfCode = function (langCode) {
      var raw = String(langCode || 'en').trim();
      if (!raw) return 'EN';
      var short = raw.split('-')[0].toUpperCase();
      if (short === 'EN' || short === 'DE' || short === 'ES' || short === 'IT' || short === 'FR') return short;
      return 'EN';
    };
    var buildDocsFallbackUrl = function (kind, langCode) {
      var L = langToPdfCode(langCode);
      if (kind === 'dossier') return '/docs/RolandoGuy_Dossier_' + L + '.pdf';
      if (kind === 'artistSheet') return '/docs/RolandoGuy_ArtistSheet_' + L + '.pdf';
      return '';
    };
    var resolvePdf = function (kind, langCode) {
      var block = pdfs && pdfs[kind] ? pdfs[kind] : {};
      var rawLang = String(langCode || 'en');
      var shortLang = rawLang.split('-')[0];
      var candidates = [
        rawLang.toUpperCase(),
        rawLang.toLowerCase(),
        shortLang.toUpperCase(),
        shortLang.toLowerCase()
      ];
      for (var i = 0; i < candidates.length; i++) {
        var c = candidates[i];
        var value = normalizePdfValue(block[c]);
        if (isConfiguredPdf(value)) return value;
      }
      var keys = Object.keys(block || {});
      for (var j = 0; j < keys.length; j++) {
        if (/^en$/i.test(keys[j])) {
          var enValue = normalizePdfValue(block[keys[j]]);
          if (isConfiguredPdf(enValue)) return enValue;
        }
      }
      for (var k = 0; k < keys.length; k++) {
        var anyValue = normalizePdfValue(block[keys[k]]);
        if (isConfiguredPdf(anyValue)) return anyValue;
      }
      // Hard public fallback to known physical docs path when configured data
      // is missing/empty/malformed for the requested language.
      return buildDocsFallbackUrl(kind, langCode);
    };
    var dossierUrl = resolvePdf('dossier', lang);
    var artistUrl = resolvePdf('artistSheet', lang);
    var dossierBtn = document.getElementById('epkDossierBtn');
    var artistBtn = document.getElementById('epkArtistSheetBtn');
    var dossierSoon = document.getElementById('epkDossierSoon');
    var artistSoon = document.getElementById('epkArtistSoon');
    var soonByLang = {
      en: 'Available soon',
      de: 'Bald verfügbar',
      es: 'Disponible pronto',
      it: 'Disponibile a breve',
      fr: 'Disponible prochainement'
    };
    var normalizePdfUrl = function (url) {
      var u = String(url || '').trim();
      if (!u) return '';
      if (/^www\./i.test(u)) return 'https://' + u;
      if (/^\/\//.test(u)) return (window.location && window.location.protocol ? window.location.protocol : 'https:') + u;
      return u;
    };
    var isValidPdfUrl = function (url) {
      var u = normalizePdfUrl(url);
      if (!u) return false;
      if (/^(#|javascript:|about:blank)$/i.test(u)) return false;
      if (/placeholder|todo|coming[-_\s]?soon/i.test(u)) return false;
      if (/^data:application\/pdf/i.test(u)) return true;
      // Accept any non-placeholder HTTP(S) URL; many file services provide valid
      // download links without a .pdf suffix.
      if (/^https?:\/\//i.test(u)) return true;
      return /\.pdf(\?|#|$)/i.test(u);
    };
    var explainPdfValidity = function (url) {
      var u = normalizePdfUrl(url);
      if (!u) return 'empty';
      if (/^(#|javascript:|about:blank)$/i.test(u)) return 'blocked scheme';
      if (/placeholder|todo|coming[-_\s]?soon/i.test(u)) return 'placeholder pattern';
      if (/^data:application\/pdf/i.test(u)) return 'valid data url';
      if (/^https?:\/\//i.test(u)) return 'valid http(s) url';
      if (/\.pdf(\?|#|$)/i.test(u)) return 'valid relative pdf';
      return 'invalid format';
    };
    var bindPdfBtn = function (btn, noteEl, url, fallbackName, kind) {
      if (!btn) return;
      var normalizedUrl = normalizePdfUrl(url);
      var isValid = isValidPdfUrl(normalizedUrl);
      if (isValid) {
        var safeUrl = normalizedUrl;
        btn.href = safeUrl;
        btn.setAttribute('download', safeUrl.split('/').pop() || fallbackName);
        btn.setAttribute('target', '_blank');
        btn.setAttribute('rel', 'noopener');
        btn.classList.remove('is-disabled');
        btn.removeAttribute('aria-disabled');
        btn.removeAttribute('tabindex');
        if (noteEl) {
          noteEl.style.display = 'none';
          noteEl.textContent = '';
          noteEl.setAttribute('aria-hidden', 'true');
          noteEl.setAttribute('hidden', 'hidden');
        }
      } else {
        btn.removeAttribute('href');
        btn.removeAttribute('download');
        btn.removeAttribute('target');
        btn.removeAttribute('rel');
        btn.classList.add('is-disabled');
        btn.setAttribute('aria-disabled', 'true');
        btn.setAttribute('tabindex', '-1');
        if (noteEl) {
          var soon = mpPick(lang, 'epk.pdfSoon', soonByLang[lang] || soonByLang.en);
          noteEl.textContent = soon;
          noteEl.style.display = 'block';
          noteEl.removeAttribute('hidden');
          noteEl.setAttribute('aria-hidden', 'false');
        }
      }
    };
    bindPdfBtn(dossierBtn, dossierSoon, dossierUrl, 'Dossier.pdf', 'dossier');
    bindPdfBtn(artistBtn, artistSoon, artistUrl, 'ArtistSheet.pdf', 'artistSheet');

    var copyBtn = document.getElementById('epkCopyBtn');
    if (copyBtn) copyBtn.textContent = effectiveUiText(currentLang, 'epk.copyBio') || '\u29d6 Copy biography';
  }

  function applyPressChrome() {
    var lang = currentLang || 'en';
    var ti = uiTable(lang);
    var intro = document.getElementById('reviewsIntro');
    if (intro && MP_PRESS) {
      var ri = '';
      if (MP_PRESS.reviewsIntroByLang && typeof MP_PRESS.reviewsIntroByLang === 'object') {
        ri =
          MP_PRESS.reviewsIntroByLang[lang] ||
          MP_PRESS.reviewsIntroByLang.en ||
          '';
      }
      if (!ri && MP_PRESS.reviewsIntro) ri = MP_PRESS.reviewsIntro;
      intro.textContent = ri;
    }
    var prog = document.getElementById('epkProgramsLink');
    if (prog) {
      if (ti['epk.programsLink']) prog.textContent = ti['epk.programsLink'];
      prog.setAttribute('href', 'repertoire.html#programs');
    }
  }

  window.epkTab = epkTab;
  window.epkCopyBio = epkCopyBio;

  window.addEventListener('mp:langchange', function (e) {
    currentLang = (e.detail && e.detail.lang) || 'en';
    if (!MP_PRESS) return;
    applyPressChrome();
    renderPress();
    renderEpk();
  });

  window.addEventListener('mp:localesready', function () {
    if (typeof window.getMpSiteLang === 'function') currentLang = window.getMpSiteLang();
    if (!MP_PRESS) return;
    applyPressChrome();
    renderPress();
    renderEpk();
  });

  var epkBiosPromise = fetch('/v1-assets/data/epk-bios.json', { cache: 'no-store' })
    .then(function (r) {
      if (!r.ok) throw new Error(r.statusText);
      return r.json();
    })
    .then(normalizeEpkBiosPayload)
    .catch(function () {
      return emptyEpkBiosPool();
    });

  function bootPressPage(biosPool) {
    EPK_BIOS_POOL = biosPool;
    if (typeof window.getMpSiteLang === 'function') currentLang = window.getMpSiteLang();
    applyPressChrome();
    renderPress();
    renderEpk();
  }

  fetch('/v1-assets/data/press-data.json', { cache: 'no-store' })
    .then(function (r) {
      if (!r.ok) throw new Error(r.statusText);
      return r.json();
    })
    .catch(function () {
      var lang = (typeof window.getMpSiteLang === 'function' && window.getMpSiteLang()) || 'en';
      return {
        reviewsIntro: mpPick(lang, 'press.dataLoadError', 'Press content could not be loaded.'),
        press: [],
        pressMeta: {},
        epkPhotos: [],
        publicPdfs: {}
      };
    })
    .then(function (data) {
      MP_PRESS = data;
      return Promise.all([epkBiosPromise, loadLiveRuntimeOverrides()]);
    })
    .then(function (vals) {
      return vals[0];
    })
    .then(bootPressPage);
})();
